# Generated by Django 6.0.5 on 2026-07-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('role', models.CharField(default='Teacher', max_length=150)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='staff/')),
                ('short_bio', models.TextField()),
                ('motto', models.CharField(blank=True, max_length=255)),
                ('started_at_shhs', models.DateField(blank=True, null=True)),
                ('is_principal', models.BooleanField(default=False)),
                ('welcome_remarks', models.TextField(blank=True, help_text="Shown in the principal's welcome section.")),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-is_principal', 'display_order', 'full_name'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_principal', True)), fields=('is_principal',), name='only_one_principal')],
            },
        ),
    ]
