# Generated by Django 6.0.8 on 2026-08-18 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_alumni_directory_and_programmes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniProfileUpdateVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_digest', models.CharField(editable=False, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_update_verifications', to='alumni.alumnistory')),
            ],
            options={
                'verbose_name': 'Alumni profile update verification',
                'verbose_name_plural': 'Alumni profile update verifications',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['alumni', 'expires_at'], name='alumni_alum_alumni__6cfdfe_idx')],
            },
        ),
    ]
