# Generated by Django 6.0.5 on 2026-05-31 10:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
