# Generated by Django 6.0.5 on 2026-05-31 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='homepage_announcement',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_announcement',
            field=models.BooleanField(default=False),
        ),
    ]
