# Generated by Django 6.0.5 on 2026-05-31 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contactmessage_sitesettings_google_maps_embed_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at']},
        ),
    ]
