# Generated by Django 6.0.5 on 2026-05-31 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesettings_favicon_sitesettings_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='admissions_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
