# Generated by Django 6.0.5 on 2026-05-31 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sitesettings_admissions_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='admissions_message',
            field=models.TextField(blank=True, help_text='Message shown when admissions are closed.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='admissions_open',
            field=models.BooleanField(default=False, help_text='Controls whether online applications are being accepted.'),
        ),
    ]
