# Generated by Django 6.0.5 on 2026-07-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_sitesettings_admissions_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="about_history",
            field=models.TextField(blank=True, help_text="The school history shown on the About Us page."),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_mission",
            field=models.TextField(blank=True, help_text="The mission statement shown on the About Us page."),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_values",
            field=models.TextField(blank=True, help_text="The school values shown on the About Us page. Enter one value per line."),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="about_vision",
            field=models.TextField(blank=True, help_text="The vision statement shown on the About Us page."),
        ),
    ]
