# Generated by Django 6.0.5 on 2026-07-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_sitesettings_about_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtracurricularActivity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("category", models.CharField(choices=[("music", "Music and performance"), ("sport", "Sport"), ("academic", "Academic club"), ("service", "Service and leadership"), ("culture", "Culture and society"), ("other", "Other")], default="other", max_length=20)),
                ("short_description", models.CharField(help_text="A short selling point shown on activity cards.", max_length=240)),
                ("description", models.TextField(help_text="Describe what the activity offers and how learners benefit.")),
                ("achievements", models.TextField(blank=True, help_text="Notable awards, performances or milestones. Enter one achievement per line.")),
                ("featured_image", models.ImageField(blank=True, help_text="A wide, high-quality image works best.", null=True, upload_to="activities/")),
                ("is_featured", models.BooleanField(default=False, help_text="Show this activity as a selling point on the homepage.")),
                ("is_published", models.BooleanField(default=True, help_text="Allow visitors to see this activity on the public website.")),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Club or activity",
                "verbose_name_plural": "Clubs and activities",
                "ordering": ("display_order", "name"),
            },
        ),
    ]
