# Generated by Django 6.0.8 on 2026-08-16 20:36

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_sitesettings_admissions_closing_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicFormRateLimitBucket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier_hash", models.CharField(max_length=64, unique=True)),
                ("window_started_at", models.DateTimeField()),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Public form rate-limit bucket",
                "verbose_name_plural": "Public form rate-limit buckets",
            },
        ),
        migrations.CreateModel(
            name="PublicFormSubmissionToken",
            fields=[
                (
                    "token_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("scope", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["scope", "created_at"],
                        name="core_public_scope_7f66e0_idx",
                    )
                ],
            },
        ),
    ]
