"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from django.core.exceptions import ImproperlyConfigured
from django.utils.csp import CSP
from decouple import Csv, config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DJANGO_DEBUG", default=False, cast=bool)
ENVIRONMENT = config(
    "DJANGO_ENVIRONMENT",
    default="development" if DEBUG else "production",
).lower()

ALLOWED_HOSTS = config(
    "ALLOWED_HOSTS",
    default="localhost,127.0.0.1",
    cast=Csv(),
)

CSRF_TRUSTED_ORIGINS = config(
    "CSRF_TRUSTED_ORIGINS",
    default="",
    cast=Csv(),
)

# Django's development server serves plain HTTP. Keep HTTPS-only behavior off
# locally; production settings should override these values explicitly.
SECURE_SSL_REDIRECT = config(
    "DJANGO_SECURE_SSL_REDIRECT",
    default=not DEBUG,
    cast=bool,
)
SESSION_COOKIE_SECURE = config(
    "DJANGO_SESSION_COOKIE_SECURE",
    default=not DEBUG,
    cast=bool,
)
CSRF_COOKIE_SECURE = config(
    "DJANGO_CSRF_COOKIE_SECURE",
    default=not DEBUG,
    cast=bool,
)
SECURE_HSTS_SECONDS = config(
    "DJANGO_SECURE_HSTS_SECONDS",
    default=31536000 if not DEBUG else 0,
    cast=int,
)
SECURE_HSTS_INCLUDE_SUBDOMAINS = config(
    "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS",
    default=False,
    cast=bool,
)
SECURE_HSTS_PRELOAD = config(
    "DJANGO_SECURE_HSTS_PRELOAD",
    default=False,
    cast=bool,
)
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True
X_FRAME_OPTIONS = "DENY"
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_AGE = config("DJANGO_SESSION_COOKIE_AGE", default=8 * 60 * 60, cast=int)

if ENVIRONMENT == "production":
    insecure_settings = []
    if DEBUG:
        insecure_settings.append("DJANGO_DEBUG must be False")
    if not SECURE_SSL_REDIRECT:
        insecure_settings.append("DJANGO_SECURE_SSL_REDIRECT must be True")
    if not SESSION_COOKIE_SECURE:
        insecure_settings.append("DJANGO_SESSION_COOKIE_SECURE must be True")
    if not CSRF_COOKIE_SECURE:
        insecure_settings.append("DJANGO_CSRF_COOKIE_SECURE must be True")
    if SECURE_HSTS_SECONDS <= 0:
        insecure_settings.append("DJANGO_SECURE_HSTS_SECONDS must be greater than zero")
    if insecure_settings:
        raise ImproperlyConfigured(
            "Unsafe production configuration: " + "; ".join(insecure_settings)
        )


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',

    "apps.core",
    "apps.accounts",
    "apps.pages",
    "apps.posts",
    "apps.events",
    "apps.academics",
    "apps.staff",
    "apps.admissions",
    "apps.alumni",
    "apps.vacancies.apps.VacanciesConfig",
    "apps.portal",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.csp.ContentSecurityPolicyMiddleware',
    'apps.core.middleware.PermissionsPolicyMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.csp',
                'apps.core.context_processors.site_settings',
                'apps.portal.context_processors.portal_stats',
            ],
        },
    },
]

# Scripts are restricted to same-origin files and per-response nonces on
# intentional inline scripts. Inline scripts and styles are otherwise blocked.
SECURE_CSP = {
    "default-src": [CSP.SELF],
    "base-uri": [CSP.SELF],
    "connect-src": [CSP.SELF],
    "font-src": [CSP.SELF, "https://fonts.gstatic.com"],
    "form-action": [CSP.SELF],
    "frame-ancestors": [CSP.NONE],
    "frame-src": [CSP.SELF, "https://www.google.com"],
    "img-src": [CSP.SELF, "data:"],
    "media-src": [CSP.SELF],
    "object-src": [CSP.NONE],
    "script-src": [CSP.SELF, CSP.NONCE],
    "style-src": [CSP.SELF, "https://fonts.googleapis.com"],
}

PERMISSIONS_POLICY = ", ".join(
    (
        "accelerometer=()",
        "ambient-light-sensor=()",
        "autoplay=()",
        "camera=()",
        "display-capture=()",
        "encrypted-media=()",
        "fullscreen=()",
        "gamepad=()",
        "geolocation=()",
        "gyroscope=()",
        "magnetometer=()",
        "microphone=()",
        "midi=()",
        "payment=()",
        "picture-in-picture=()",
        "publickey-credentials-create=()",
        "publickey-credentials-get=()",
        "screen-wake-lock=()",
        "serial=()",
        "usb=()",
        "web-share=()",
        "xr-spatial-tracking=()",
    )
)

WSGI_APPLICATION = 'config.wsgi.application'

LOGIN_URL = "staff-login"
LOGIN_REDIRECT_URL = "dashboard"
LOGOUT_REDIRECT_URL = "home"

# Outbound application receipts. Credentials must be supplied through the
# deployment environment and must never be stored in SiteSettings or Git.
EMAIL_BACKEND = config(
    "EMAIL_BACKEND",
    default=(
        "django.core.mail.backends.console.EmailBackend"
        if DEBUG
        else "django.core.mail.backends.smtp.EmailBackend"
    ),
)
EMAIL_HOST = config("EMAIL_HOST", default="")
EMAIL_PORT = config("EMAIL_PORT", default=587, cast=int)
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")
EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=True, cast=bool)
EMAIL_USE_SSL = config("EMAIL_USE_SSL", default=False, cast=bool)
EMAIL_TIMEOUT = config("EMAIL_TIMEOUT", default=10, cast=int)
DEFAULT_FROM_EMAIL = config(
    "DEFAULT_FROM_EMAIL",
    default="Sacred Heart Admissions <no-reply@localhost>",
)
SERVER_EMAIL = config("SERVER_EMAIL", default=DEFAULT_FROM_EMAIL)


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
        'CONN_MAX_AGE': config('DB_CONN_MAX_AGE', default=60, cast=int),
        'CONN_HEALTH_CHECKS': True,
        'OPTIONS': {
            'charset': 'utf8mb4',
            'connect_timeout': 10,
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# A filesystem cache is shared by Passenger workers and supports the anonymous
# request throttles. Set a private, writable path outside the public web root.
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
        "LOCATION": config(
            "DJANGO_CACHE_LOCATION",
            default=str(BASE_DIR / ".django-cache"),
        ),
        "TIMEOUT": 3600,
        "OPTIONS": {"MAX_ENTRIES": 10000},
    }
}
RATELIMIT_TRUSTED_PROXY_DEPTH = config(
    "DJANGO_RATELIMIT_TRUSTED_PROXY_DEPTH",
    default=0,
    cast=int,
)


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = "Africa/Maseru"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = config("STATIC_URL", default="/static/")

STATICFILES_DIRS = [
    ("css", BASE_DIR / "static" / "css"),
    ("admin", BASE_DIR / "static" / "admin"),
]

STATIC_ROOT = Path(
    config("STATIC_ROOT", default=str(BASE_DIR / "staticfiles"))
).expanduser()

# Let WhiteNoise fall back to Django's static-file finders when a cPanel
# deployment has not populated STATIC_ROOT yet. collectstatic remains the
# preferred production path, but this prevents an unstyled site after deploys.
WHITENOISE_USE_FINDERS = config(
    "WHITENOISE_USE_FINDERS",
    default=True,
    cast=bool,
)

MEDIA_URL = config("MEDIA_URL", default="/media/")

MEDIA_ROOT = Path(
    config("MEDIA_ROOT", default=str(BASE_DIR / "media"))
).expanduser()

# cPanel normally serves MEDIA_ROOT through Apache. Some Passenger setups send
# /media/ to Django instead, so retain a controlled application fallback.
SERVE_MEDIA = config(
    "DJANGO_SERVE_MEDIA",
    default=True,
    cast=bool,
)

STORAGES = {
    "default": {
        "BACKEND": "apps.core.storage.SafeMediaStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

WHITENOISE_MAX_AGE = 31536000 if not DEBUG else 0
WHITENOISE_KEEP_ONLY_HASHED_FILES = not DEBUG

# Uploaded media is untrusted. Apache must serve it as static data and must
# never execute scripts from MEDIA_ROOT (see deployment/media.htaccess).
FILE_UPLOAD_PERMISSIONS = 0o644
FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o755
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "production": {
            "format": "{levelname} {asctime} {name}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "production",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": config("DJANGO_LOG_LEVEL", default="INFO"),
    },
    "loggers": {
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
    },
}
