# Generated by Django 6.0.5 on 2026-05-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=10)),
                ('student_name', models.CharField(max_length=100)),
                ('student_surname', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('parent_guardian_names', models.CharField(max_length=255)),
                ('parent_phone_number', models.CharField(max_length=30)),
                ('home_address', models.TextField()),
                ('previous_school', models.CharField(max_length=255)),
                ('district', models.CharField(choices=[('Berea', 'Berea'), ('Butha-Buthe', 'Butha-Buthe'), ('Leribe', 'Leribe'), ('Mafeteng', 'Mafeteng'), ('Maseru', 'Maseru'), ("Mohale's Hoek", "Mohale's Hoek"), ('Mokhotlong', 'Mokhotlong'), ("Qacha's Nek", "Qacha's Nek"), ('Quthing', 'Quthing'), ('Thaba-Tseka', 'Thaba-Tseka')], max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
