# Generated by Django 6.0.5 on 2026-05-31 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='reference_number',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('review', 'Under Review'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='new', max_length=20),
        ),
    ]
