# Generated by Django 6.0.5 on 2026-05-31 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_application_notes_application_reference_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='reference_number',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
