# Generated by Django 6.0.5 on 2026-05-31 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_alter_application_reference_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='reference_number',
            field=models.CharField(blank=True, default='temp', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
