# Generated by Django 6.0.8 on 2026-08-09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admissions", "0008_application_nationality_and_candidate_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="district",
            field=models.CharField(
                choices=[
                    ("Berea", "Berea"),
                    ("Butha-Buthe", "Butha-Buthe"),
                    ("Leribe", "Leribe"),
                    ("Mafeteng", "Mafeteng"),
                    ("Maseru", "Maseru"),
                    ("Mohale's Hoek", "Mohale's Hoek"),
                    ("Mokhotlong", "Mokhotlong"),
                    ("Qacha's Nek", "Qacha's Nek"),
                    ("Quthing", "Quthing"),
                    ("Thaba-Tseka", "Thaba-Tseka"),
                    ("Other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="parent_guardian_email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                verbose_name="Parent/guardian email",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="parent_guardian_names",
            field=models.CharField(
                max_length=255,
                verbose_name="Parent/guardian name",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="parent_phone_number",
            field=models.CharField(
                max_length=30,
                verbose_name="Parent/guardian phone number",
            ),
        ),
    ]
