# Generated by Django 6.0.8 on 2026-09-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0010_application_submission_protection'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='boarding_required',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='', max_length=3, verbose_name='Boarding/accommodation required'),
        ),
    ]
